# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 11:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiKey', models.CharField(max_length=64)),
                ('allowedPacks', models.ManyToManyField(related_name='allowedPacks', to='epu.Pack')),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='packuser',
            name='allowedPacks',
        ),
        migrations.RemoveField(
            model_name='packuser',
            name='user',
        ),
        migrations.DeleteModel(
            name='PackUser',
        ),
    ]
