# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epu', '0003_authkeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authkeys',
            name='expires',
            field=models.DateTimeField(),
        ),
    ]
