# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-24 15:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epu', '0004_auto_20171124_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authkeys',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
