# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-27 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epu', '0008_auto_20171126_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='changelist',
        ),
        migrations.AddField(
            model_name='pack',
            name='updaterBinaries',
            field=models.FileField(default='/dev/null', upload_to='epu/zips/'),
            preserve_default=False,
        ),
    ]
