# Generated by Django 3.2.4 on 2021-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epu', '0010_pack_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apiKey',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
